"""Solved Seed file

Revision ID: 2e26d8119bd0
Revises: b83067c51b53
Create Date: 2023-12-12 17:54:13.450638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e26d8119bd0'
down_revision: Union[str, None] = 'b83067c51b53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'first_name',
               existing_type=sa.VARCHAR(length=25))
    op.alter_column('customers', 'last_name',
               existing_type=sa.VARCHAR(length=25))
    op.alter_column('restaurants', 'name',
               existing_type=sa.VARCHAR(length=250))
    op.alter_column('reviews', 'comments',
               existing_type=sa.VARCHAR(length=300))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reviews', 'comments',
               existing_type=sa.VARCHAR(length=300))
    op.alter_column('restaurants', 'name',
               existing_type=sa.VARCHAR(length=250))
    op.alter_column('customers', 'last_name',
               existing_type=sa.VARCHAR(length=25))
    op.alter_column('customers', 'first_name',
               existing_type=sa.VARCHAR(length=25))
    # ### end Alembic commands ###
